-- Migration: 0041_invoices
-- Creates invoices and invoice_line_items tables

CREATE TABLE IF NOT EXISTS `invoices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `companyId` int NOT NULL,
  `invoiceNumber` varchar(50) NOT NULL,
  `customerOrgId` int,
  `siteId` int,
  `jobId` int,
  `approvedWorkId` int,
  `workOrderId` int,
  `quoteId` int,
  `status` enum('draft','sent','viewed','approved','paid','partial','overdue','void') NOT NULL DEFAULT 'draft',
  `billToName` varchar(255),
  `billToAddress` text,
  `billToCity` varchar(100),
  `billToState` varchar(100),
  `billToPostalCode` varchar(20),
  `billToEmail` varchar(320),
  `invoiceDate` timestamp NULL,
  `dueDate` timestamp NULL,
  `paidAt` timestamp NULL,
  `sentAt` timestamp NULL,
  `subtotal` decimal(10,2) DEFAULT '0.00',
  `taxRate` decimal(5,4) DEFAULT '0.0000',
  `taxAmount` decimal(10,2) DEFAULT '0.00',
  `total` decimal(10,2) DEFAULT '0.00',
  `amountPaid` decimal(10,2) DEFAULT '0.00',
  `balanceDue` decimal(10,2) DEFAULT '0.00',
  `sageCustomerCode` varchar(50),
  `sageGlCode` varchar(50),
  `sageDepartment` varchar(50),
  `sageExportedAt` timestamp NULL,
  `sageExportStatus` enum('pending','exported','error') DEFAULT 'pending',
  `internalNotes` text,
  `clientNotes` text,
  `createdById` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `invoices_companyId_idx` (`companyId`),
  KEY `invoices_status_idx` (`status`),
  KEY `invoices_customerOrgId_idx` (`customerOrgId`)
);

CREATE TABLE IF NOT EXISTS `invoice_line_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `invoiceId` int NOT NULL,
  `sortOrder` int DEFAULT 0,
  `description` text NOT NULL,
  `quantity` decimal(10,2) DEFAULT '1.00',
  `unitPrice` decimal(10,2) DEFAULT '0.00',
  `total` decimal(10,2) DEFAULT '0.00',
  `taxable` tinyint(1) DEFAULT 1,
  `sageGlCode` varchar(50),
  `sageDepartment` varchar(50),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `invoice_line_items_invoiceId_idx` (`invoiceId`)
);
