CREATE TABLE `feedback_items` (
  `id` int NOT NULL AUTO_INCREMENT,
  `companyId` int NOT NULL,
  `submittedById` int NOT NULL,
  `assignedToId` int DEFAULT NULL,
  `type` enum('bug','feature_request','confusing_workflow','data_issue','report_output_issue','mobile_issue','performance_issue','other') NOT NULL DEFAULT 'other',
  `status` enum('new','reviewed','in_progress','resolved','closed','wont_fix') NOT NULL DEFAULT 'new',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `pageUrl` varchar(500) DEFAULT NULL,
  `routeName` varchar(200) DEFAULT NULL,
  `entityType` varchar(100) DEFAULT NULL,
  `entityId` int DEFAULT NULL,
  `browserInfo` varchar(500) DEFAULT NULL,
  `deviceInfo` varchar(200) DEFAULT NULL,
  `adminNotes` text DEFAULT NULL,
  `resolvedAt` timestamp DEFAULT NULL,
  `resolvedById` int DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fi_companyId_idx` (`companyId`),
  KEY `fi_submittedBy_idx` (`submittedById`),
  KEY `fi_status_idx` (`companyId`, `status`)
);
