// Synthetic full MySQL backup/restore + post-backup receipt recovery.
// Requires the explicitly local Docker MySQL service, never production.
import { spawn } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { createReadStream, createWriteStream } from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import mysql from 'mysql2/promise';
import { drizzle } from 'drizzle-orm/mysql2';
import { migrate } from 'drizzle-orm/mysql2/migrator';
const url=new URL(process.env.DATABASE_URL??'');
if(!['127.0.0.1','localhost'].includes(url.hostname)||!url.pathname.startsWith('/inspectra_'))throw Error('Explicit isolated loopback Inspectra database required');
const sourceName=`inspectra_restore_source_${process.pid}`, restoredName=`inspectra_restore_target_${process.pid}`;
url.pathname='/';const admin=await mysql.createConnection(url.toString());
const folder=await mkdtemp(join(tmpdir(),'inspectra-backup-')),dump=join(folder,'synthetic.sql');let source,restored;
const dockerArgs=['--host=unix:///var/run/docker.sock','exec'];
const localEnv={...process.env};for(const key of ['DOCKER_HOST','DOCKER_CONTEXT','DOCKER_TLS','DOCKER_TLS_VERIFY','DOCKER_CERT_PATH'])delete localEnv[key];
async function command(args,input,output){const child=spawn('docker',[...dockerArgs,...args],{env:localEnv,stdio:['pipe','pipe','pipe']});let stderr='';child.stderr.on('data',c=>{stderr+=c});const done=new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',code=>code===0?resolve():reject(Error(`Local backup command failed (${code}): ${stderr}`)))});if(input)await pipeline(createReadStream(input),child.stdin);else child.stdin.end();if(output)await pipeline(child.stdout,createWriteStream(output));else child.stdout.resume();await done;}
async function state(c){const counts={};for(const table of ['companies','customer_orgs','sites','jobs','invoices','invoice_line_items','invoice_payments','fire_alarm_inspection_results']){const [rows]=await c.query(`SELECT COUNT(*) count FROM \`${table}\``);counts[table]=rows[0].count}const [invoices]=await c.query('SELECT id,companyId,customerOrgId,total,amountPaid,balanceDue,status,paidAt FROM invoices ORDER BY id');const [receipts]=await c.query('SELECT * FROM invoice_payments ORDER BY id');const [snapshots]=await c.query('SELECT * FROM fire_alarm_inspection_results ORDER BY id');const [triggers]=await c.query("SELECT TRIGGER_NAME,ACTION_STATEMENT FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA=DATABASE() AND TRIGGER_NAME LIKE 'inspectra_%' ORDER BY TRIGGER_NAME");return {counts,invoices,receipts,snapshots,triggers};}
async function payment(c,requestId,amount,totalPaid){await c.beginTransaction();try{await c.query('SET @inspectra_payment_protocol=2');await c.query('SELECT id FROM invoices WHERE id=1 FOR UPDATE');await c.query('INSERT INTO invoice_payments(invoiceId,requestId,amount,result,recordedById) VALUES(1,?,?,?,1)',[requestId,amount,JSON.stringify({success:true,total:100,amountPaid:totalPaid,balanceDue:100-totalPaid,status:'partial',operationPaidAt:null})]);await c.query('UPDATE invoices SET amountPaid=?,balanceDue=?,status=\'partial\' WHERE id=1',[totalPaid,100-totalPaid]);await c.commit()}catch(e){await c.rollback();throw e}finally{await c.query('SET @inspectra_payment_protocol=NULL')}}
try{
 await admin.query(`CREATE DATABASE \`${sourceName}\``);url.pathname='/'+sourceName;source=await mysql.createConnection(url.toString());await migrate(drizzle(source),{migrationsFolder:'drizzle'});
 await source.query("INSERT INTO companies(id,name) VALUES(1,'Restore A'),(2,'Restore B')");await source.query("INSERT INTO customer_orgs(id,companyId,name) VALUES(1,1,'Org A'),(2,2,'Org B')");await source.query("INSERT INTO sites(id,companyId,customerOrgId,name) VALUES(1,1,1,'Site A')");await source.query("INSERT INTO jobs(id,companyId,customerOrgId,siteId,jobNumber,title,finalizedAt) VALUES(1,1,1,1,'RESTORE-1','Original inspection','2026-01-01')");
 await source.query("INSERT INTO invoices(id,companyId,customerOrgId,invoiceNumber,total,amountPaid,balanceDue,status) VALUES(1,1,1,'RESTORE-1',100,20,80,'partial'),(2,2,2,'RESTORE-2',200,50,150,'partial')");await source.query("INSERT INTO invoice_line_items(invoiceId,description,quantity,unitPrice,total,taxable) VALUES(1,'Work',1,100,100,false)");
 await source.query("INSERT INTO fire_alarm_inspection_results(jobId,fireAlarmSystemId,checklistItemId,result,notes,itemSnapshot) VALUES(1,1,1,'fail','Original answer',JSON_OBJECT('captureProvenance','captured','sectionName','Original','sectionOrder',1,'itemDescription','Original question','requirementType','test','isRequired',true,'standardVersion','2019'))");
 const first=randomUUID();await payment(source,first,30,50);const backupState=await state(source);
 await command(['inspectra-onboarding-mysql','mysqldump','-uroot','--single-transaction','--routines','--triggers','--no-tablespaces','--set-gtid-purged=OFF',sourceName],null,dump);
 const postBackup=randomUUID();await payment(source,postBackup,25,75);const latest=await state(source);
 await admin.query(`CREATE DATABASE \`${restoredName}\``);await command(['-i','inspectra-onboarding-mysql','mysql','-uroot',restoredName],dump);url.pathname='/'+restoredName;restored=await mysql.createConnection(url.toString());assert.deepEqual(await state(restored),backupState);console.log('PASS: full mysqldump restores counts, totals, tenant ownership, immutable snapshots, receipt history and all four guard definitions');
 assert.notDeepEqual((await state(restored)).invoices,latest.invoices);console.log('PASS: a pre-payment backup is explicitly detected as stale after a new cumulative receipt; blind old-version rollback would lose $25');
 await assert.rejects(restored.query('UPDATE invoices SET amountPaid=25,balanceDue=75 WHERE id=1'));await assert.rejects(restored.query('DELETE FROM invoice_payments WHERE invoiceId=1'));console.log('PASS: restored guards reject old writers and receipt deletion');
 const exported=latest.receipts.find(row=>row.requestId===postBackup);assert(exported);
 async function reconcile(){await restored.beginTransaction();try{await restored.query('SET @inspectra_payment_protocol=2');const [locked]=await restored.query('SELECT companyId,customerOrgId FROM invoices WHERE id=1 FOR UPDATE');assert.equal(locked[0].companyId,latest.invoices[0].companyId);assert.equal(locked[0].customerOrgId,latest.invoices[0].customerOrgId);const [existing]=await restored.query('SELECT result FROM invoice_payments WHERE invoiceId=1 AND requestId=?',[postBackup]);if(existing.length)assert.deepEqual(existing[0].result,exported.result);else{await restored.query('INSERT INTO invoice_payments(id,invoiceId,requestId,amount,result,recordedById,recordedAt) VALUES(?,?,?,?,?,?,?)',[exported.id,exported.invoiceId,exported.requestId,exported.amount,JSON.stringify(exported.result),exported.recordedById,exported.recordedAt]);await restored.query('UPDATE invoices SET amountPaid=?,balanceDue=?,status=? WHERE id=1',[exported.result.amountPaid,exported.result.balanceDue,exported.result.status]);}await restored.commit()}catch(e){await restored.rollback();throw e}finally{await restored.query('SET @inspectra_payment_protocol=NULL')}}
 await reconcile();await reconcile();assert.deepEqual(await state(restored),latest);console.log('PASS: reviewed synthetic post-backup receipt forward recovery restores $75 total exactly once, preserving historical baseline, tenants and snapshots');
 console.log('PASS: isolated backup/restore rehearsal only; sanitized production data, PITR and real accounting-source reconciliation remain unrun');
}finally{await source?.end();await restored?.end();for(const name of [sourceName,restoredName])await admin.query(`DROP DATABASE IF EXISTS \`${name}\``);await admin.end();await rm(folder,{recursive:true,force:true})}
