/**
 * scripts/generatePrebuiltTemplateMigration.ts
 *
 * Emits an idempotent, plain-MySQL back-fill migration for pre-built inspection
 * templates (stdout). Used to generate
 * drizzle/migrations/0083_seed_nfpa_ulc_template_library.sql from
 * server/seeds/nfpaTemplateLibrary.ts — rerun it (redirecting to a new numbered
 * file) whenever templates are added to the library.
 *
 * Guards: template by (companyId, name); section by (templateId, title); item
 * by (sectionId, sortOrder). companyId/templateId/sectionId always derive from
 * the parent row, never hardcoded, so the output is companyId-safe and can be
 * re-run against a partially applied database.
 *
 * Usage:
 *   npx tsx scripts/generatePrebuiltTemplateMigration.ts > drizzle/migrations/0083_....sql
 */
import { NFPA_TEMPLATE_LIBRARY, type TemplateDef } from "../server/seeds/nfpaTemplateLibrary.js";

// Same exclusion as server/seeds/provisionTemplates.ts: the library's NFPA 10
// entry is superseded by the seeds/nfpa10Extinguisher.ts template (migration 0082).
const TEMPLATES: TemplateDef[] = NFPA_TEMPLATE_LIBRARY.filter(
  (t) => t.name !== "NFPA 10 — Portable Fire Extinguisher Annual Inspection",
);

/** Escape a string for a single-quoted MySQL literal. */
function q(v: string): string {
  return `'${v.replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
}
function qOrNull(v: string | null | undefined): string {
  return v == null ? "NULL" : q(v);
}
function jsonOrNull(v: unknown): string {
  return v == null ? "NULL" : q(JSON.stringify(v));
}

const out: string[] = [];
const totalItems = TEMPLATES.reduce((n, t) => n + t.sections.reduce((m, s) => m + s.items.length, 0), 0);

out.push(`-- NFPA / ULC Pre-Built Inspection Template Library — Back-fill Seed`);
out.push(`-- Migration: 0083_seed_nfpa_ulc_template_library.sql`);
out.push(`-- GENERATED by scripts/generatePrebuiltTemplateMigration.ts from`);
out.push(`-- server/seeds/nfpaTemplateLibrary.ts — do not edit by hand; regenerate instead.`);
out.push(`--`);
out.push(`-- ${TEMPLATES.length} templates, ${totalItems} items. Installs one copy per EXISTING company`);
out.push(`-- (companies created later receive the library from the company.create provisioning`);
out.push(`-- hook, server/seeds/provisionTemplates.ts). Every INSERT is guarded by NOT EXISTS`);
out.push(`-- and ids derive from parent rows, so the file is idempotent and companyId-safe.`);
out.push(`-- The library's NFPA 10 entry is excluded — migration 0082 already ships NFPA 10.`);
out.push(`-- No assignments are seeded (the matcher ignores systemType; a systemType-only`);
out.push(`-- assignment would attach every template to every job). Offices assign templates`);
out.push(`-- from the admin Templates UI.`);
out.push(``);

for (const tpl of TEMPLATES) {
  // Guard-key sanity: section titles must be unique within the template, or the
  // NOT EXISTS guards would silently skip a second section of the same name.
  const titles = tpl.sections.map((s) => s.title);
  if (new Set(titles).size !== titles.length) {
    throw new Error(`Duplicate section titles in template "${tpl.name}"`);
  }

  const tplName = q(tpl.name);
  out.push(`-- ═══ ${tpl.name} ═══`);
  out.push(`INSERT INTO \`inspection_templates\``);
  out.push(`  (\`companyId\`, \`name\`, \`description\`, \`systemType\`, \`inspectionType\`, \`frequency\`, \`version\`, \`status\`, \`isDefault\`, \`createdById\`)`);
  out.push(`SELECT c.\`id\`, ${tplName}, ${q(tpl.description)}, ${q(tpl.systemType)}, ${q(tpl.inspectionType)}, ${q(tpl.frequency)}, 1, 'active', 0, NULL`);
  out.push(`FROM \`companies\` c`);
  out.push(`WHERE NOT EXISTS (SELECT 1 FROM \`inspection_templates\` t WHERE t.\`companyId\` = c.\`id\` AND t.\`name\` = ${tplName});`);
  out.push(``);

  for (const [sectionIdx, section] of tpl.sections.entries()) {
    const secTitle = q(section.title);
    out.push(`INSERT INTO \`inspection_template_sections\` (\`companyId\`, \`templateId\`, \`title\`, \`description\`, \`sortOrder\`, \`isRequired\`)`);
    out.push(`SELECT t.\`companyId\`, t.\`id\`, ${secTitle}, ${qOrNull(section.description)}, ${sectionIdx}, 1`);
    out.push(`FROM \`inspection_templates\` t`);
    out.push(`WHERE t.\`name\` = ${tplName}`);
    out.push(`  AND NOT EXISTS (SELECT 1 FROM \`inspection_template_sections\` s WHERE s.\`templateId\` = t.\`id\` AND s.\`title\` = ${secTitle});`);
    out.push(``);

    for (const [itemIdx, item] of section.items.entries()) {
      out.push(`INSERT INTO \`inspection_template_items\``);
      out.push(`  (\`companyId\`, \`templateId\`, \`sectionId\`, \`itemCode\`, \`questionText\`, \`helpText\`, \`responseType\`, \`isRequired\`, \`sortOrder\`, \`deficiencyTrigger\`, \`options\`, \`codeReference\`)`);
      out.push(
        `SELECT s.\`companyId\`, s.\`templateId\`, s.\`id\`, ${qOrNull(item.itemCode)}, ${q(item.questionText)}, ${qOrNull(item.helpText)}, ${q(item.responseType)}, ${item.isRequired !== false ? 1 : 0}, ${itemIdx}, ${jsonOrNull(item.deficiencyTrigger)}, ${jsonOrNull(item.options)}, ${qOrNull(item.codeReference)}`,
      );
      out.push(`FROM \`inspection_template_sections\` s JOIN \`inspection_templates\` t ON t.\`id\` = s.\`templateId\``);
      out.push(`WHERE t.\`name\` = ${tplName} AND s.\`title\` = ${secTitle}`);
      out.push(`  AND NOT EXISTS (SELECT 1 FROM \`inspection_template_items\` i WHERE i.\`sectionId\` = s.\`id\` AND i.\`sortOrder\` = ${itemIdx});`);
      out.push(``);
    }
  }
}

out.push(`-- Verify (per company): ${TEMPLATES.length} templates, ${totalItems} items`);
out.push(`-- SELECT COUNT(*) FROM inspection_templates WHERE name IN (${TEMPLATES.map((t) => q(t.name)).join(", ")});`);

process.stdout.write(out.join("\n") + "\n");
